### ISSUE TITLE
Trying to dockerise this script - env vars

### ISSUE THREAD

**Issue by psyciknz** [tdharris/cloudflare-uptimerobot#1]
Will this command `const apiKey = Deno.env.get("CLOUDFLARE_API_KEY") || "";` pull from an environment variable, or only from a .env file?

I don't have any typescript processes, so rather than trying to install deno I've tried an alpine deno container.   

I have th efollowing so far:
```
FROM denoland/deno:alpine
RUN apk add git
RUN git clone https://github.com/tdharris/cloudflare-uptimerobot.git
WORKDIR cloudflare-uptimerobot/src
USER deno
CMD ["run", "--allow-net", "--allow-env","--allow-read","--watch", "main.ts"]
```
For the dockerfile and a compose of:
```
cfuptimerobot:
    container_name: cfuptimerobot
    build:
      context: cfrobot/docker
      dockerfile: Dockerfile
    mem_limit: 50m
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_DOMAIN=${DOMAIN}
```
Where those vars are them pushed into the container.  But that makes them environment vars.
